//
// Created by matt on 15/4/20.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_GLOBALS_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_GLOBALS_H

#define LOG_LEVEL SPDLOG_LEVEL_DEBUG

#define SPDLOG_ACTIVE_LEVEL LOG_LEVEL
#include <spdlog/spdlog.h>

namespace normal::expression {}

#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_GLOBALS_H
