//
// Created by Yifei Yang on 4/20/22.
//

#ifndef FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_GROUP_GROUPKERNELTYPE_H
#define FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_GROUP_GROUPKERNELTYPE_H

namespace fpdb::executor::physical::group {

enum GroupKernelType{
  GROUP_KERNEL,
  GROUP_ARROW_KERNEL
};

}

#endif //FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_GROUP_GROUPKERNELTYPE_H
