//
// Created by Yifei Yang on 1/17/22.
//

#ifndef FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H
#define FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H

namespace fpdb::executor::physical {

enum POpType {
  AGGREGATE,
  CACHE_LOAD,
  COLLATE,
  COLLECT,
  LOCAL_FILE_SCAN,
  REMOTE_FILE_SCAN,
  FILTER,
  GROUP,
  HASH_JOIN_BUILD,
  HASH_JOIN_PROBE,
  HASH_JOIN_ARROW,
  NESTED_LOOP_JOIN,
  LIMIT_SORT,
  MERGE,
  PROJECT,
  S3_GET,
  S3_SELECT,
  SHUFFLE,
  SHUFFLE_BATCH_LOAD,
  SORT,
  SPLIT,
  BLOOM_FILTER_CREATE,
  BLOOM_FILTER_USE,
  FPDB_STORE_FILE_SCAN,
  FPDB_STORE_SUPER,
  FPDB_STORE_TABLE_CACHE_LOAD
};

}

#endif //FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H
