//
// Created by Yifei Yang on 1/17/22.
//

#ifndef FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H
#define FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H

namespace fpdb::executor::physical {

enum POpType {
  AGGREGATE,
  CACHE_LOAD,
  COLLATE,
  LOCAL_FILE_SCAN,
  REMOTE_FILE_SCAN,
  FILTER,
  GROUP,
  HASH_JOIN_BUILD,
  HASH_JOIN_PROBE,
  HASH_JOIN_ARROW,
  NESTED_LOOP_JOIN,
  LIMIT_SORT,
  MERGE,
  PROJECT,
  TUPLESET_SIZE_PROJECT,
  S3_GET,
  S3_SELECT,
  SHUFFLE,
  SORT,
  SPLIT,
  NODEWISE_SPLIT,
  BLOOM_FILTER_CREATE,
  BLOOM_FILTER_USE,
  BLOOM_FILTER_SPLIT,
  BLOOM_FILTER_CONCAT,
  GLOBAL_BLOOM_FILTER_INIT,
  GLOBAL_BLOOM_FILTER_FINALIZE,
  DIST_GLOBAL_BLOOM_FILTER_INIT,
  DIST_GLOBAL_BLOOM_FILTER_MERGE,
  BROADCAST,
  BATCH_EXCHANGE,
  BATCH_EXCHANGE_RR_FORWARD,
  FPDB_STORE_FILE_SCAN,
  FPDB_STORE_SUPER,
  FPDB_STORE_SHUFFLE_BATCH_LOAD,
  FPDB_STORE_TABLE_CACHE_LOAD,
  ADAPT_SINK
};

}

#endif //FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H
