//
// Created by Yifei Yang on 5/1/22.
//

#ifndef FPDB_FPDB_STORE_SERVER_INCLUDE_FPDB_STORE_SERVER_FLIGHT_BITMAPTYPE_H
#define FPDB_FPDB_STORE_SERVER_INCLUDE_FPDB_STORE_SERVER_FLIGHT_BITMAPTYPE_H

namespace fpdb::store::server::flight {

enum BitmapType {
  FILTER_COMPUTE,
  FILTER_STORAGE,
  BLOOM_FILTER_COMPUTE
};

}

#endif //FPDB_FPDB_STORE_SERVER_INCLUDE_FPDB_STORE_SERVER_FLIGHT_BITMAPTYPE_H
