//
// Created by Yifei Yang on 11/2/21.
//

#ifndef FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_AGGREGATEPREPFUNCTIONTYPE_H
#define FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_AGGREGATEPREPFUNCTIONTYPE_H

namespace fpdb::plan::prephysical {

enum AggregatePrePFunctionType {
  SUM,
  COUNT,
  MAX,
  MIN,
  AVG
};

}


#endif //FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_AGGREGATEPREPFUNCTIONTYPE_H
