//
// Created by Yifei Yang on 11/1/21.
//

#ifndef FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_PREPOPTYPE_H
#define FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_PREPOPTYPE_H

namespace fpdb::plan::prephysical {

enum PrePOpType {
  FILTERABLE_SCAN,
  FILTER,
  HASH_JOIN,
  NESTED_LOOP_JOIN,
  AGGREGATE,
  GROUP,
  SORT,
  LIMIT_SORT,
  PROJECT,
  SEPARABLE_SUPER
};

}

#endif //FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_PREPOPTYPE_H
