//
// Created by Yifei Yang on 11/8/21.
//

#ifndef FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_CATALOGUEENTRYTYPE_H
#define FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_CATALOGUEENTRYTYPE_H

namespace fpdb::catalogue {

enum CatalogueEntryType {
  LOCAL_FS,
  OBJ_STORE
};

}

#endif //FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_CATALOGUEENTRYTYPE_H
