//
// Created by matt on 15/4/20.
//

#ifndef FPDB_FPDB_CONNECTOR_INCLUDE_FPDB_CONNECTOR_GLOBALS_H
#define FPDB_FPDB_CONNECTOR_INCLUDE_FPDB_CONNECTOR_GLOBALS_H

#define LOG_LEVEL SPDLOG_LEVEL_DEBUG

#define SPDLOG_ACTIVE_LEVEL LOG_LEVEL
#include <spdlog/spdlog.h>

namespace fpdb::connector {}

#endif //FPDB_FPDB_CONNECTOR_INCLUDE_FPDB_CONNECTOR_GLOBALS_H
