//
// Created by Yifei Yang on 2/28/22.
//

#ifndef FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_OBJ_STORE_OBJSTORETYPE_H
#define FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_OBJ_STORE_OBJSTORETYPE_H

namespace fpdb::catalogue::obj_store {

enum class ObjStoreType {
  S3,
  FPDB_STORE
};

}

#endif //FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_OBJ_STORE_OBJSTORETYPE_H
