//
// Created by Yifei Yang on 2/13/22.
//

#ifndef FPDB_FPDB_TUPLE_INCLUDE_FPDB_TUPLE_FILEFORMATTYPE_H
#define FPDB_FPDB_TUPLE_INCLUDE_FPDB_TUPLE_FILEFORMATTYPE_H

namespace fpdb::tuple {

enum class FileFormatType {
  CSV,
  PARQUET
};

}

#endif // FPDB_FPDB_TUPLE_INCLUDE_FPDB_TUPLE_FILEFORMATTYPE_H
