//
// Created by matt on 5/3/20.
//

#ifndef NORMAL_NORMAL_SQL_INCLUDE_NORMAL_SQL__GLOBALS_H
#define NORMAL_NORMAL_SQL_INCLUDE_NORMAL_SQL__GLOBALS_H

#define LOG_LEVEL SPDLOG_LEVEL_DEBUG

#define SPDLOG_ACTIVE_LEVEL LOG_LEVEL
#include <spdlog/spdlog.h>

namespace normal::sql {}

#endif //NORMAL_NORMAL_SQL_INCLUDE_NORMAL_SQL__GLOBALS_H
