//
// Created by matt on 5/3/20.
//

#ifndef NORMAL_NORMAL_TEST_INCLUDE_NORMAL_TEST_GLOBALS_H
#define NORMAL_NORMAL_TEST_INCLUDE_NORMAL_TEST_GLOBALS_H

#define LOG_LEVEL SPDLOG_LEVEL_DEBUG

#define SPDLOG_ACTIVE_LEVEL LOG_LEVEL
#include <spdlog/spdlog.h>

namespace normal::test {}

#endif //NORMAL_NORMAL_TEST_INCLUDE_NORMAL_TEST_GLOBALS_H
